apiVersion: v1
kind: Service
metadata:
 name: client
spec:
 ports:
 - port: 8080
   name: http
 type: LoadBalancer
 selector:
  app: kanaszta
  tier: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: client
spec:
 replicas: 1
 selector:
  matchLabels:
   app: kanaszta
   tier: client
 template:
  metadata:
   labels:
    app: kanaszta
    tier: client
  spec:
   containers:
   - name: client
     image: gcr.io/tribal-booth-155221/kanaszta-client
  # - name: server
  #   image: gcr.io/tribal-booth-155221/kanaszta-server
