apiVersion: v1
kind: Service
metadata:
 name: server
spec:
 ports:
 - port: 3001
   name: server
 type: LoadBalancer
 selector:
  app: kanaszta
  tier: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: server
spec:
 replicas: 1
 selector:
  matchLabels:
   app: kanaszta
   tier: server
 template:
  metadata:
   labels:
    app: kanaszta
    tier: server
  spec:
   containers:
   - name: server
     image: gcr.io/tribal-booth-155221/kanaszta-server
